### ISSUE TITLE
How to get squad (de, hi, es)?

### ISSUE THREAD

**Issue by ax-22** [ishan00/meta-learning-for-multi-task-multilingual#1]
Would you please advise how to get the following three-language translation of squad? 
de_squad-translate-train-train-v1.1.json
hi_squad-translate-train-train-v1.1.json
es_squad-translate-train-train-v1.1.json

**Comment by ishan00** [comment]
Hello, the datasets are not officially released but you can get it by contacting the authors of XTREME (https://arxiv.org/abs/2003.11080)
